# fly.toml app configuration file generated for rs-blog on 2023-05-02T09:51:10-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rs-blog"
primary_region = "ord"

[deploy]
  release_command = "./build.sh"
